# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1287, 819)
        MainWindow.setMinimumSize(QtCore.QSize(1287, 819))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.HTtempscroll = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.HTtempscroll.setGeometry(QtCore.QRect(180, 690, 71, 32))
        self.HTtempscroll.setStyleSheet("font: 75 italic 12pt \"PibotoLt\";\n"
"font: 12pt \"PibotoLt\";")
        self.HTtempscroll.setObjectName("HTtempscroll")
        self.LTtempscroll = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.LTtempscroll.setGeometry(QtCore.QRect(180, 750, 71, 32))
        self.LTtempscroll.setObjectName("LTtempscroll")
        self.HTtemp = QtWidgets.QLabel(self.centralwidget)
        self.HTtemp.setGeometry(QtCore.QRect(60, 690, 111, 22))
        self.HTtemp.setObjectName("HTtemp")
        self.LTtemp = QtWidgets.QLabel(self.centralwidget)
        self.LTtemp.setGeometry(QtCore.QRect(60, 750, 111, 22))
        self.LTtemp.setObjectName("LTtemp")
        self.LTtemp_2 = QtWidgets.QLabel(self.centralwidget)
        self.LTtemp_2.setGeometry(QtCore.QRect(980, 750, 111, 22))
        self.LTtemp_2.setObjectName("LTtemp_2")
        self.HThumscroll = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.HThumscroll.setGeometry(QtCore.QRect(1100, 690, 71, 32))
        self.HThumscroll.setObjectName("HThumscroll")
        self.LThumscroll = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.LThumscroll.setGeometry(QtCore.QRect(1100, 750, 71, 32))
        self.LThumscroll.setObjectName("LThumscroll")
        self.HThum = QtWidgets.QLabel(self.centralwidget)
        self.HThum.setGeometry(QtCore.QRect(980, 690, 111, 22))
        self.HThum.setObjectName("HThum")
        self.tempbutton = QtWidgets.QPushButton(self.centralwidget)
        self.tempbutton.setGeometry(QtCore.QRect(40, 610, 106, 30))
        self.tempbutton.setObjectName("tempbutton")
        self.humbutton = QtWidgets.QPushButton(self.centralwidget)
        self.humbutton.setGeometry(QtCore.QRect(1030, 620, 99, 30))
        self.humbutton.setObjectName("humbutton")
        self.refb = QtWidgets.QPushButton(self.centralwidget)
        self.refb.setGeometry(QtCore.QRect(1080, 120, 99, 30))
        self.refb.setObjectName("refb")
        self.Alarm = QtWidgets.QLineEdit(self.centralwidget)
        self.Alarm.setGeometry(QtCore.QRect(550, 670, 161, 61))
        self.Alarm.setObjectName("Alarm")
        self.ctof = QtWidgets.QPushButton(self.centralwidget)
        self.ctof.setGeometry(QtCore.QRect(230, 610, 101, 30))
        self.ctof.setObjectName("ctof")
        self.statusedit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.statusedit.setGeometry(QtCore.QRect(740, 60, 271, 151))
        self.statusedit.setObjectName("statusedit")
        self.statuslabel = QtWidgets.QLabel(self.centralwidget)
        self.statuslabel.setGeometry(QtCore.QRect(820, 20, 111, 22))
        self.statuslabel.setObjectName("statuslabel")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(300, 40, 113, 32))
        self.lineEdit.setObjectName("lineEdit")
        self.Humlabel = QtWidgets.QLabel(self.centralwidget)
        self.Humlabel.setGeometry(QtCore.QRect(190, 90, 71, 22))
        self.Humlabel.setTextFormat(QtCore.Qt.AutoText)
        self.Humlabel.setObjectName("Humlabel")
        self.getvalb = QtWidgets.QPushButton(self.centralwidget)
        self.getvalb.setGeometry(QtCore.QRect(230, 180, 99, 30))
        self.getvalb.setObjectName("getvalb")
        self.templabel = QtWidgets.QLabel(self.centralwidget)
        self.templabel.setGeometry(QtCore.QRect(190, 130, 101, 22))
        self.templabel.setObjectName("templabel")
        self.tempval = QtWidgets.QLineEdit(self.centralwidget)
        self.tempval.setGeometry(QtCore.QRect(300, 120, 91, 32))
        self.tempval.setObjectName("tempval")
        self.humval = QtWidgets.QLineEdit(self.centralwidget)
        self.humval.setGeometry(QtCore.QRect(300, 80, 81, 32))
        self.humval.setObjectName("humval")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 50, 68, 22))
        self.label.setObjectName("label")
        self.widget = MplWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 269, 611, 311))
        self.widget.setObjectName("widget")
        self.widget_2 = MplWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(710, 270, 561, 311))
        self.widget_2.setObjectName("widget_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.HTtemp.setText(_translate("MainWindow", "High Threshold:"))
        self.LTtemp.setText(_translate("MainWindow", "Low Threshold :"))
        self.LTtemp_2.setText(_translate("MainWindow", "Low Threshold :"))
        self.HThum.setText(_translate("MainWindow", "High Threshold:"))
        self.tempbutton.setText(_translate("MainWindow", "Temperature"))
        self.humbutton.setText(_translate("MainWindow", "Humidity"))
        self.refb.setText(_translate("MainWindow", "Refresh"))
        self.ctof.setText(_translate("MainWindow", "Toggle Unit"))
        self.statuslabel.setText(_translate("MainWindow", "Sensor Status :"))
        self.Humlabel.setText(_translate("MainWindow", "Humidity : "))
        self.getvalb.setText(_translate("MainWindow", "Get Values"))
        self.templabel.setText(_translate("MainWindow", "Temperature :"))
        self.label.setText(_translate("MainWindow", "Time :"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

